#! /usr/bin/env node
var data = require('./setup.json');
var fs = require('fs');
data.server_ip = process.argv[2];
if(process.argv[3]){
    data.server_port = parseInt(process.argv[3]);
} else {
    data.server_port = 3000;
}
data.osc = null;
console.log("Successfully set server IP address to "+ data.server_ip + " and port to: " + data.server_port);
fs.writeFile(__dirname +'/setup.json', JSON.stringify(data), function(e){});