#! /usr/bin/env node
const utils = require('./utils.js');
const rl = utils.readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

const main = async () => {
    await utils.setosc(rl).then((e) => {
        rl.close();
    });
}

main();